import React, { useState } from 'react';
import { Alert, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { Feather } from '@expo/vector-icons';
import { router } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useTheme } from '../../context/ThemeContext';
import { supabase } from '../../utils/supabase';

export default function SuporteScreen(){const {theme}=useTheme();const insets=useSafeAreaInsets();const[subject,setSubject]=useState('');const[description,setDescription]=useState('');const[busy,setBusy]=useState(false);const submit=async()=>{if(subject.trim().length<5||description.trim().length<10)return Alert.alert('Revise o chamado','Informe assunto e detalhes do problema.');setBusy(true);const{data,error}=await supabase.rpc('open_support_ticket',{p_category:'app',p_subject:subject.trim(),p_description:description.trim(),p_priority:'normal'});setBusy(false);if(error)return Alert.alert('Erro',error.message);Alert.alert('Chamado aberto',`Protocolo ${data?.public_code||''}`,[{text:'OK',onPress:()=>router.back()}]);};return <View style={[styles.container,{backgroundColor:theme.background}]}><View style={[styles.header,{paddingTop:insets.top+10,borderBottomColor:theme.border}]}><TouchableOpacity onPress={()=>router.back()}><Feather name="arrow-left" size={22} color={theme.text}/></TouchableOpacity><Text style={[styles.title,{color:theme.text}]}>Suporte</Text></View><View style={styles.content}><Text style={[styles.label,{color:theme.text}]}>Assunto</Text><TextInput value={subject} onChangeText={setSubject} style={[styles.input,{color:theme.text,borderColor:theme.border,backgroundColor:theme.surface}]} placeholder="Ex.: problema com convite" placeholderTextColor={theme.muted}/><Text style={[styles.label,{color:theme.text}]}>Detalhes</Text><TextInput value={description} onChangeText={setDescription} multiline style={[styles.input,styles.description,{color:theme.text,borderColor:theme.border,backgroundColor:theme.surface}]} placeholder="Descreva o que aconteceu" placeholderTextColor={theme.muted}/><TouchableOpacity disabled={busy} onPress={submit} style={[styles.button,{backgroundColor:theme.primary,opacity:busy?.6:1}]}><Text style={styles.buttonText}>{busy?'Enviando…':'Abrir chamado'}</Text></TouchableOpacity></View></View>}
const styles=StyleSheet.create({container:{flex:1},header:{paddingHorizontal:20,paddingBottom:16,flexDirection:'row',alignItems:'center',gap:16,borderBottomWidth:1},title:{fontSize:21,fontWeight:'800'},content:{padding:20},label:{fontSize:13,fontWeight:'700',marginTop:14,marginBottom:7},input:{minHeight:50,borderWidth:1,borderRadius:12,paddingHorizontal:14,paddingVertical:12},description:{height:160,textAlignVertical:'top'},button:{height:54,borderRadius:14,alignItems:'center',justifyContent:'center',marginTop:20},buttonText:{color:'#fff',fontWeight:'800'}});
