import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { DataTable, EmptyState, ErrorState, FilterBar, LoadingState, StatusBadge } from '@/components/ui/AsyncState';
import { jsonArray, jsonObject, jsonString } from '@/lib/json';
import { supabase } from '@/lib/supabase';

interface AuditRow { source: string; id: string; type: string; entity: string; entityId: string | null; actor: string; result: string; reason: string | null; createdAt: string }

export function AuditPage() {
  const [search, setSearch] = useState(''); const [source, setSource] = useState(''); const [result, setResult] = useState(''); const [from, setFrom] = useState(''); const [to, setTo] = useState('');
  const query = useQuery({ queryKey: ['audit-timeline', search, source, result, from, to], queryFn: async () => { const { data, error } = await supabase.rpc('list_internal_audit_timeline', { p_search: search || undefined, p_source: source || undefined, p_result: result || undefined, p_from: from ? new Date(from).toISOString() : undefined, p_to: to ? new Date(`${to}T23:59:59`).toISOString() : undefined, p_limit: 250 }); if (error) throw error; return jsonArray(data).map(jsonObject).filter(Boolean).map((row): AuditRow => ({ source: jsonString(row?.source) || 'internal', id: jsonString(row?.event_id) || crypto.randomUUID(), type: jsonString(row?.event_type) || 'evento', entity: jsonString(row?.entity_type) || '—', entityId: jsonString(row?.entity_id), actor: jsonString(row?.actor_name) || 'Sistema', result: jsonString(row?.result) || 'allowed', reason: jsonString(row?.reason), createdAt: jsonString(row?.created_at) || new Date(0).toISOString() })); } });
  return <section><div className="mb-5"><h2 className="text-2xl font-bold">Auditoria</h2><p className="mt-1 text-sm text-slate-500">Timeline global de clientes, assinaturas, suporte, sessões, staff, builds e configuração.</p></div><FilterBar><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Ação, ator ou alvo" aria-label="Buscar auditoria" className="h-10 rounded-lg border px-3"/><select value={source} onChange={(e) => setSource(e.target.value)} aria-label="Fonte" className="h-10 rounded-lg border px-3"><option value="">Todas as fontes</option><option value="internal">Interna</option><option value="commercial">Comercial</option><option value="support">Suporte</option></select><select value={result} onChange={(e) => setResult(e.target.value)} aria-label="Resultado" className="h-10 rounded-lg border px-3"><option value="">Todos os resultados</option><option value="allowed">Permitido</option><option value="denied">Negado</option><option value="failed">Falhou</option></select><div className="grid grid-cols-2 gap-2"><input type="date" value={from} onChange={(e) => setFrom(e.target.value)} aria-label="Data inicial" className="h-10 rounded-lg border px-2"/><input type="date" value={to} onChange={(e) => setTo(e.target.value)} aria-label="Data final" className="h-10 rounded-lg border px-2"/></div></FilterBar>{query.isLoading ? <LoadingState/> : query.isError ? <ErrorState error={query.error}/> : !query.data?.length ? <EmptyState title="Sem eventos" description="Nenhum evento corresponde aos filtros."/> : <DataTable headers={['Data','Fonte','Ação','Ator','Alvo','Resultado','Motivo']} minWidth={980}>{query.data.map((row) => <tr key={`${row.source}-${row.id}`} className="border-t"><td className="p-3 text-xs">{new Date(row.createdAt).toLocaleString('pt-BR')}</td><td className="p-3"><StatusBadge value={row.source}/></td><td className="p-3 font-medium">{row.type}</td><td className="p-3">{row.actor}</td><td className="p-3 text-xs">{row.entity}{row.entityId ? ` · ${row.entityId.slice(0, 12)}` : ''}</td><td className="p-3"><StatusBadge value={row.result}/></td><td className="max-w-xs truncate p-3 text-xs" title={row.reason || ''}>{row.reason || '—'}</td></tr>)}</DataTable>}</section>;
}
