import { useMemo, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Eye, Plus } from 'lucide-react';
import { HighRiskDialog } from '@/components/ui/HighRiskDialog';
import { DataTable, EmptyState, ErrorState, LoadingState, StatusBadge } from '@/components/ui/AsyncState';
import { useAuth } from '@/contexts/AuthContext';
import { useAdministrativeMutation } from '@/hooks/useAdministrativeMutation';
import { jsonArray, jsonBoolean, jsonNumber, jsonObject, jsonString } from '@/lib/json';
import { supabase } from '@/lib/supabase';
import type { Json } from '@/types/supabase';

interface FormVersion { version:number; status:string; reason:string; createdAt:string }
interface FormRow { id:string; title:string; description:string|null; status:string; active:boolean; municipality:string|null; version:number; questions:Json; classification:Json; phases:Json; calculationType:string; updatedAt:string; versions:FormVersion[] }

function parseForms(value:Json|null):FormRow[]{return jsonArray(value).map(jsonObject).filter(Boolean).map(row=>({id:jsonString(row?.id)||'',title:jsonString(row?.title)||'Formulário',description:jsonString(row?.description),status:jsonString(row?.status)||'rascunho',active:jsonBoolean(row?.active)||false,municipality:jsonString(row?.municipality),version:jsonNumber(row?.version)||1,questions:row?.questions??[],classification:row?.classification??{},phases:row?.phases??[],calculationType:jsonString(row?.calculation_type)||'soma_total',updatedAt:jsonString(row?.updated_at)||new Date(0).toISOString(),versions:jsonArray(row?.versions).map(jsonObject).filter(Boolean).map(v=>({version:jsonNumber(v?.version)||0,status:jsonString(v?.status)||'rascunho',reason:jsonString(v?.reason)||'',createdAt:jsonString(v?.created_at)||new Date(0).toISOString()}))}));}

export function FormsPage(){const{can}=useAuth();const[editing,setEditing]=useState<FormRow|'new'|null>(null);const[pending,setPending]=useState<{form:FormRow;action:'publish'|'rollback';version?:number}|null>(null);const query=useQuery({queryKey:['internal-forms'],queryFn:async()=>{const{data,error}=await supabase.rpc('list_internal_forms');if(error)throw error;return parseForms(data);}});const mutation=useAdministrativeMutation<{formId:string|null;action:string;payload:Json;reason:string},unknown>({mutationFn:async(input,operationId)=>{const{data,error}=await supabase.rpc('mutate_internal_form',{p_form_id:input.formId||'',p_action:input.action,p_payload:input.payload,p_reason:input.reason,p_operation_id:operationId});if(error)throw error;return data;},invalidate:[['internal-forms'],['audit-timeline']]});async function mutate(formId:string|null,action:string,payload:Json,reason:string){const result=await mutation.mutateAsync({formId,action,payload,reason});if(!result.ok)throw new Error(result.error);}
  if(query.isLoading)return <LoadingState label="Carregando formulários…"/>;if(query.isError)return <ErrorState error={query.error}/>;return <section><div className="mb-5 flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-2xl font-bold">Formulários</h2><p className="mt-1 text-sm text-slate-500">Catálogo versionado com validação, pré-visualização, publicação e rollback.</p></div>{(can('configuration.prepare')||can('configuration.publish'))&&<button onClick={()=>setEditing('new')} className="flex items-center gap-2 rounded-lg bg-blue-700 px-4 py-2 text-sm font-bold text-white"><Plus className="h-4 w-4"/>Novo formulário</button>}</div>{!query.data?.length?<EmptyState title="Sem formulários" description="Crie o primeiro formulário como rascunho."/>:<DataTable headers={['Formulário','Município','Versão','Status','Atualização','Ações']} minWidth={900}>{query.data.map(form=><tr key={form.id} className="border-t"><td className="p-3"><b>{form.title}</b><p className="max-w-md truncate text-xs text-slate-500">{form.description||'Sem descrição'}</p></td><td className="p-3">{form.municipality||'Global'}</td><td className="p-3">v{form.version}</td><td className="p-3"><StatusBadge value={form.status}/></td><td className="p-3 text-xs">{new Date(form.updatedAt).toLocaleString('pt-BR')}</td><td className="p-3"><div className="flex flex-wrap gap-2"><button onClick={()=>setEditing(form)} className="rounded-lg border px-2 py-1 text-xs font-semibold">Editar/visualizar</button>{can('configuration.publish')&&<button onClick={()=>setPending({form,action:'publish'})} disabled={form.status==='publicado'} className="rounded-lg border px-2 py-1 text-xs font-semibold text-emerald-700 disabled:opacity-40">Publicar</button>}{can('configuration.publish')&&form.versions.length>1&&<select defaultValue="" onChange={e=>{if(e.target.value)setPending({form,action:'rollback',version:Number(e.target.value)});}} aria-label={`Rollback de ${form.title}`} className="rounded-lg border px-2 py-1 text-xs"><option value="">Rollback…</option>{form.versions.slice(1).map(v=><option key={v.version} value={v.version}>v{v.version}</option>)}</select>}</div></td></tr>)}</DataTable>}{editing&&<FormEditor form={editing==='new'?undefined:editing} onClose={()=>setEditing(null)} onSave={async(payload,reason)=>{await mutate(editing==='new'?null:editing.id,editing==='new'?'create':'save_draft',payload,reason);setEditing(null);}}/>}{pending&&<HighRiskDialog open title={pending.action==='publish'?'Publicar formulário':'Restaurar versão do formulário'} description="A versão será preservada no histórico e a operação ficará na auditoria." confirmLabel={pending.action==='publish'?'Publicar':'Restaurar e publicar'} onClose={()=>setPending(null)} onConfirm={async reason=>{await mutate(pending.form.id,pending.action,pending.action==='rollback'?{version:pending.version??1}:{},reason);setPending(null);}}/>}</section>;
}

function FormEditor({form,onClose,onSave}:{form?:FormRow;onClose:()=>void;onSave:(payload:Json,reason:string)=>Promise<void>}){const[title,setTitle]=useState(form?.title||'');const[description,setDescription]=useState(form?.description||'');const[municipality,setMunicipality]=useState(form?.municipality||'');const[calculation,setCalculation]=useState(form?.calculationType||'soma_total');const[questions,setQuestions]=useState(JSON.stringify(form?.questions??[],null,2));const[classification,setClassification]=useState(JSON.stringify(form?.classification??{},null,2));const[phases,setPhases]=useState(JSON.stringify(form?.phases??[],null,2));const[confirming,setConfirming]=useState(false);const[error,setError]=useState<string|null>(null);const preview=useMemo(()=>questionPreview(phases,questions),[phases,questions]);function payload():Json{if(title.trim().length<3)throw new Error('Informe um título com pelo menos 3 caracteres.');const q=JSON.parse(questions) as Json;const c=JSON.parse(classification) as Json;const p=JSON.parse(phases) as Json;if(!Array.isArray(q)||!Array.isArray(p))throw new Error('Perguntas e fases devem ser arrays JSON.');return{title:title.trim(),description:description.trim(),municipality:municipality.trim(),calculation_type:calculation,questions:q,classification:c,phases:p};}
  return <><div className="fixed inset-0 z-50 grid place-items-center bg-black/50 p-4"><div role="dialog" aria-modal="true" aria-labelledby="form-editor-title" className="max-h-[94vh] w-full max-w-5xl overflow-y-auto rounded-2xl bg-white p-6"><h3 id="form-editor-title" className="text-xl font-bold">{form?'Editar formulário':'Novo formulário'}</h3><div className="mt-4 grid gap-4 md:grid-cols-3"><Field label="Título" value={title} onChange={setTitle}/><Field label="Município (vazio = global)" value={municipality} onChange={setMunicipality}/><label className="text-sm"><span className="font-semibold">Tipo de cálculo</span><select value={calculation} onChange={e=>setCalculation(e.target.value)} className="mt-1 h-10 w-full rounded-lg border px-3"><option value="soma_total">Soma total</option><option value="ponderada_max_elemento">Ponderada por fase</option></select></label><label className="md:col-span-3 text-sm"><span className="font-semibold">Descrição</span><textarea value={description} onChange={e=>setDescription(e.target.value)} rows={2} className="mt-1 w-full rounded-lg border p-3"/></label></div><div className="mt-4 grid gap-4 lg:grid-cols-3"><JsonField label="Perguntas" value={questions} onChange={setQuestions}/><JsonField label="Fases" value={phases} onChange={setPhases}/><JsonField label="Classificação" value={classification} onChange={setClassification}/></div><div className="mt-4 rounded-xl border bg-slate-50 p-4"><p className="flex items-center gap-2 font-bold"><Eye className="h-4 w-4"/>Pré-visualização</p>{preview.length?<ol className="mt-2 list-decimal space-y-1 pl-5 text-sm">{preview.slice(0,20).map((item,index)=><li key={`${item}-${index}`}>{item}</li>)}</ol>:<p className="mt-2 text-sm text-slate-500">Nenhuma pergunta reconhecida no JSON.</p>}</div>{error&&<p className="mt-3 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="mt-5 flex justify-end gap-2"><button onClick={onClose} className="rounded-lg border px-4 py-2">Cancelar</button><button onClick={()=>{try{payload();setError(null);setConfirming(true);}catch(e){setError(e instanceof Error?e.message:'JSON inválido.');}}} className="rounded-lg bg-blue-700 px-4 py-2 font-bold text-white">Salvar rascunho</button></div></div></div><HighRiskDialog open={confirming} title="Confirmar rascunho" description="O conteúdo será validado e uma nova versão ficará no histórico." confirmLabel="Salvar versão" onClose={()=>setConfirming(false)} onConfirm={async reason=>{await onSave(payload(),reason);setConfirming(false);}}/></>;
}
function questionPreview(phases:string,questions:string){try{const phaseJson=JSON.parse(phases) as Array<{perguntas?:Array<{texto?:string;pergunta?:string;label?:string}>}>;const nested=phaseJson.flatMap(f=>f.perguntas||[]);const flat=JSON.parse(questions) as Array<{texto?:string;pergunta?:string;label?:string}>;return(nested.length?nested:flat).map(q=>q.texto||q.pergunta||q.label||'Pergunta sem título');}catch{return[];}}
function Field({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="text-sm"><span className="font-semibold">{label}</span><input value={value} onChange={e=>onChange(e.target.value)} className="mt-1 h-10 w-full rounded-lg border px-3"/></label>;}
function JsonField({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="text-sm"><span className="font-semibold">{label} (JSON)</span><textarea value={value} onChange={e=>onChange(e.target.value)} rows={14} spellCheck={false} className="mt-1 w-full rounded-lg border p-3 font-mono text-xs"/></label>;}
