import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import { EmptyState, ErrorState, FilterBar, LoadingState, StatusBadge } from '@/components/ui/AsyncState';
import { jsonArray, jsonObject, jsonString } from '@/lib/json';
import { supabase } from '@/lib/supabase';

interface EventRow { id: string; version: string | null; platform: string; category: string; severity: string; correlation: string | null; summary: string; occurredAt: string; customerId: string | null; customerName: string | null }

export function TechnicalEventsPage({ category: fixedCategory, title }: { category?: string; title: string }) {
  const [customer, setCustomer] = useState(''); const [version, setVersion] = useState(''); const [platform, setPlatform] = useState(''); const [category, setCategory] = useState(fixedCategory || ''); const [severity, setSeverity] = useState(''); const [from, setFrom] = useState(''); const [to, setTo] = useState('');
  const query = useQuery({ queryKey: ['technical-events', customer, version, platform, category, severity, from, to], queryFn: async () => { const { data, error } = await supabase.rpc('list_internal_technical_events', { p_customer_id: customer || undefined, p_version: version || undefined, p_platform: platform || undefined, p_category: category || undefined, p_severity: severity || undefined, p_from: from ? new Date(from).toISOString() : undefined, p_to: to ? new Date(`${to}T23:59:59`).toISOString() : undefined, p_limit: 250 }); if (error) throw error; return jsonArray(data).map(jsonObject).filter(Boolean).map((row): EventRow => ({ id: jsonString(row?.id) || jsonString(row?.event_key) || crypto.randomUUID(), version: jsonString(row?.app_version), platform: jsonString(row?.platform) || 'unknown', category: jsonString(row?.category) || 'runtime', severity: jsonString(row?.severity) || 'info', correlation: jsonString(row?.correlation_id), summary: jsonString(row?.summary) || 'Evento técnico', occurredAt: jsonString(row?.occurred_at) || new Date(0).toISOString(), customerId: jsonString(row?.customer_id), customerName: jsonString(row?.customer_name) })); } });
  return <section><div className="mb-5"><h2 className="text-2xl font-bold">{title}</h2><p className="mt-1 text-sm text-slate-500">Eventos persistidos e sanitizados; indisponibilidade nunca é substituída por dados simulados.</p></div><FilterBar><input value={customer} onChange={(e) => setCustomer(e.target.value)} placeholder="ID do cliente" aria-label="Filtrar cliente" className="h-10 rounded-lg border px-3"/><input value={version} onChange={(e) => setVersion(e.target.value)} placeholder="Versão do app" aria-label="Filtrar versão" className="h-10 rounded-lg border px-3"/><select value={platform} onChange={(e) => setPlatform(e.target.value)} aria-label="Filtrar plataforma" className="h-10 rounded-lg border px-3"><option value="">Plataformas</option>{['android','ios','web','server','unknown'].map(v => <option key={v}>{v}</option>)}</select>{!fixedCategory && <select value={category} onChange={(e) => setCategory(e.target.value)} aria-label="Filtrar categoria" className="h-10 rounded-lg border px-3"><option value="">Categorias</option>{['version','build','sync','storage','runtime','configuration'].map(v => <option key={v}>{v}</option>)}</select>}<select value={severity} onChange={(e) => setSeverity(e.target.value)} aria-label="Filtrar severidade" className="h-10 rounded-lg border px-3"><option value="">Severidades</option>{['debug','info','warning','error','critical'].map(v => <option key={v}>{v}</option>)}</select><input type="date" value={from} onChange={(e) => setFrom(e.target.value)} aria-label="Data inicial" className="h-10 rounded-lg border px-3"/><input type="date" value={to} onChange={(e) => setTo(e.target.value)} aria-label="Data final" className="h-10 rounded-lg border px-3"/></FilterBar>{query.isLoading ? <LoadingState/> : query.isError ? <ErrorState error={query.error} onRetry={() => void query.refetch()}/> : !query.data?.length ? <EmptyState title="Nenhum evento persistido" description="A fonte respondeu sem eventos para os filtros selecionados."/> : <div className="space-y-3">{query.data.map((event) => <article key={event.id} className="rounded-xl border bg-white p-4"><div className="flex flex-wrap items-center gap-2"><StatusBadge value={event.severity}/><span className="text-xs font-semibold uppercase text-slate-500">{event.category} · {event.platform}</span><time className="ml-auto text-xs text-slate-500">{new Date(event.occurredAt).toLocaleString('pt-BR')}</time></div><p className="mt-2 font-semibold">{event.summary}</p><div className="mt-1 flex flex-wrap items-center gap-2 text-xs text-slate-500"><span>Versão {event.version || '—'} · Correlação {event.correlation || event.id}</span>{event.customerId && <Link className="font-semibold text-blue-700" to={`/clientes/${encodeURIComponent(event.customerId)}`}>{event.customerName || 'Abrir cliente'}</Link>}</div></article>)}</div>}</section>;
}
