-- Internal console identities and authorization boundaries.
-- The legacy owner_admins gate remains available while VITE_INTERNAL_CONSOLE_V2
-- is in pilot, but every new internal operation uses internal_staff.

CREATE SCHEMA IF NOT EXISTS private;
REVOKE ALL ON SCHEMA private FROM PUBLIC, anon;

CREATE TABLE public.internal_staff (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
  role text NOT NULL CHECK (role IN ('owner', 'developer', 'support', 'auditor')),
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'suspended', 'removed')),
  display_name text,
  created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX internal_staff_role_status_idx ON public.internal_staff(role, status);

CREATE TABLE public.internal_access_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  actor_role text,
  action text NOT NULL,
  target_type text,
  target_id text,
  result text NOT NULL CHECK (result IN ('allowed', 'denied', 'failed')),
  reason text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(metadata) = 'object'),
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX internal_access_events_actor_created_idx
  ON public.internal_access_events(actor_id, created_at DESC);
CREATE INDEX internal_access_events_target_created_idx
  ON public.internal_access_events(target_type, target_id, created_at DESC);

CREATE TABLE public.internal_sensitive_access (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  staff_user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  customer_key text NOT NULL CHECK (customer_key ~ '^(organization|user):[0-9a-f-]{36}$'),
  ticket_id uuid NOT NULL REFERENCES public.support_tickets(id) ON DELETE CASCADE,
  reason text NOT NULL CHECK (char_length(trim(reason)) BETWEEN 8 AND 500),
  granted_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL,
  revoked_at timestamptz,
  CHECK (expires_at > granted_at)
);
CREATE INDEX internal_sensitive_access_active_idx
  ON public.internal_sensitive_access(staff_user_id, customer_key, expires_at DESC)
  WHERE revoked_at IS NULL;

CREATE TABLE public.internal_operations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  operation_id uuid NOT NULL,
  actor_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  action text NOT NULL,
  request_hash text NOT NULL,
  status text NOT NULL DEFAULT 'processing' CHECK (status IN ('processing', 'succeeded', 'failed')),
  result jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz,
  UNIQUE (actor_id, operation_id)
);
CREATE INDEX internal_operations_created_idx ON public.internal_operations(created_at DESC);

CREATE TABLE public.technical_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_key uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  organization_id uuid REFERENCES public.organizations(id) ON DELETE SET NULL,
  user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  app_version text,
  platform text NOT NULL CHECK (platform IN ('android', 'ios', 'web', 'server', 'unknown')),
  category text NOT NULL CHECK (category IN ('version', 'build', 'sync', 'storage', 'runtime', 'configuration')),
  severity text NOT NULL CHECK (severity IN ('debug', 'info', 'warning', 'error', 'critical')),
  correlation_id text,
  summary text NOT NULL CHECK (char_length(summary) BETWEEN 1 AND 500),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(metadata) = 'object'),
  occurred_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX technical_events_filters_idx
  ON public.technical_events(category, severity, occurred_at DESC);
CREATE INDEX technical_events_org_occurred_idx
  ON public.technical_events(organization_id, occurred_at DESC);
CREATE INDEX technical_events_version_platform_idx
  ON public.technical_events(app_version, platform, occurred_at DESC);
CREATE INDEX technical_events_correlation_idx
  ON public.technical_events(correlation_id) WHERE correlation_id IS NOT NULL;

CREATE TABLE public.internal_build_requests (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  operation_id uuid NOT NULL,
  requested_by uuid NOT NULL REFERENCES auth.users(id),
  approved_by uuid REFERENCES auth.users(id),
  provider text NOT NULL CHECK (provider IN ('eas', 'github')),
  environment text NOT NULL CHECK (environment IN ('development', 'preview', 'production')),
  version text NOT NULL,
  profile text NOT NULL,
  changelog text NOT NULL DEFAULT '',
  reason text NOT NULL CHECK (char_length(trim(reason)) BETWEEN 8 AND 500),
  status text NOT NULL CHECK (status IN ('pending', 'approved', 'rejected', 'executed', 'failed')),
  created_at timestamptz NOT NULL DEFAULT now(),
  decided_at timestamptz,
  executed_at timestamptz,
  UNIQUE (requested_by, operation_id),
  CHECK (approved_by IS NULL OR approved_by <> requested_by)
);
CREATE INDEX internal_build_requests_status_created_idx
  ON public.internal_build_requests(status, created_at DESC);

-- Existing active owner records become explicit internal owner identities.
INSERT INTO public.internal_staff(user_id, role, status, display_name, created_by)
SELECT oa.user_id, 'owner', 'active', u.name, oa.created_by
FROM public.owner_admins oa
LEFT JOIN public.users u ON u.uid = oa.user_id
WHERE oa.active
ON CONFLICT (user_id) DO UPDATE
SET role = 'owner',
    status = 'active',
    display_name = COALESCE(EXCLUDED.display_name, public.internal_staff.display_name),
    updated_at = now();

CREATE OR REPLACE FUNCTION private.internal_permissions(p_role text)
RETURNS text[]
LANGUAGE sql IMMUTABLE
SET search_path = ''
AS $$
  SELECT CASE p_role
    WHEN 'owner' THEN ARRAY[
      'console.read', 'dashboard.executive.read', 'customer.read', 'customer.sensitive.read',
      'customer.write', 'commercial.read', 'commercial.write', 'support.read', 'support.write',
      'session.read', 'session.terminate', 'staff.read', 'staff.manage', 'audit.read',
      'technical.read', 'technical.write', 'build.request', 'build.approve', 'configuration.publish'
    ]::text[]
    WHEN 'developer' THEN ARRAY[
      'console.read', 'dashboard.technical.read', 'customer.read', 'customer.sensitive.request',
      'commercial.read', 'support.read', 'support.write', 'session.read', 'session.terminate',
      'audit.read', 'technical.read', 'technical.write', 'build.request', 'configuration.prepare'
    ]::text[]
    WHEN 'support' THEN ARRAY[]::text[]
    WHEN 'auditor' THEN ARRAY[]::text[]
    ELSE ARRAY[]::text[]
  END;
$$;

CREATE OR REPLACE FUNCTION private.current_internal_role(p_user_id uuid DEFAULT auth.uid())
RETURNS text
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT s.role
  FROM public.internal_staff s
  WHERE s.user_id = p_user_id AND s.status = 'active'
  LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION private.has_internal_permission(
  p_permission text,
  p_user_id uuid DEFAULT auth.uid()
)
RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT p_user_id IS NOT NULL
    AND p_permission = ANY(
      private.internal_permissions(private.current_internal_role(p_user_id))
    );
$$;

CREATE OR REPLACE FUNCTION private.has_aal2()
RETURNS boolean
LANGUAGE sql STABLE
SET search_path = ''
AS $$
  SELECT COALESCE(auth.jwt()->>'aal', 'aal1') = 'aal2';
$$;

CREATE OR REPLACE FUNCTION private.sanitize_internal_metadata(p_metadata jsonb)
RETURNS jsonb
LANGUAGE sql IMMUTABLE
SET search_path = ''
AS $$
  SELECT COALESCE(p_metadata, '{}'::jsonb) - ARRAY[
    'token', 'access_token', 'refresh_token', 'authorization', 'password', 'secret',
    'api_key', 'service_role', 'cpf', 'document', 'email', 'phone', 'photo', 'content'
  ]::text[];
$$;

CREATE OR REPLACE FUNCTION private.set_internal_updated_at()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = ''
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION private.sanitize_internal_event()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = ''
AS $$
BEGIN
  NEW.metadata := private.sanitize_internal_metadata(NEW.metadata);
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION private.can_access_sensitive_customer(
  p_customer_key text,
  p_user_id uuid DEFAULT auth.uid()
)
RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT private.has_internal_permission('customer.sensitive.read', p_user_id)
    OR EXISTS (
      SELECT 1
      FROM public.internal_sensitive_access a
      WHERE a.staff_user_id = p_user_id
        AND a.customer_key = p_customer_key
        AND a.revoked_at IS NULL
        AND a.expires_at > now()
    );
$$;

REVOKE ALL ON ALL FUNCTIONS IN SCHEMA private FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION private.current_internal_role(uuid),
  private.has_internal_permission(text, uuid), private.has_aal2(),
  private.can_access_sensitive_customer(text, uuid) TO authenticated;

CREATE TRIGGER internal_staff_set_updated_at
BEFORE UPDATE ON public.internal_staff
FOR EACH ROW EXECUTE FUNCTION private.set_internal_updated_at();
CREATE TRIGGER internal_access_events_sanitize
BEFORE INSERT OR UPDATE OF metadata ON public.internal_access_events
FOR EACH ROW EXECUTE FUNCTION private.sanitize_internal_event();
CREATE TRIGGER technical_events_sanitize
BEFORE INSERT OR UPDATE OF metadata ON public.technical_events
FOR EACH ROW EXECUTE FUNCTION private.sanitize_internal_event();

REVOKE ALL ON public.internal_staff, public.internal_access_events,
  public.internal_sensitive_access, public.internal_operations,
  public.technical_events, public.internal_build_requests FROM anon, authenticated;
GRANT SELECT ON public.internal_staff, public.internal_access_events,
  public.internal_sensitive_access, public.technical_events,
  public.internal_build_requests TO authenticated;

ALTER TABLE public.internal_staff ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.internal_access_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.internal_sensitive_access ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.internal_operations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.technical_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.internal_build_requests ENABLE ROW LEVEL SECURITY;

CREATE POLICY internal_staff_self_or_owner_select
ON public.internal_staff FOR SELECT TO authenticated
USING (user_id = (SELECT auth.uid()) OR (SELECT private.has_internal_permission('staff.read')));
CREATE POLICY internal_access_events_authorized_select
ON public.internal_access_events FOR SELECT TO authenticated
USING (actor_id = (SELECT auth.uid()) OR (SELECT private.has_internal_permission('audit.read')));
CREATE POLICY internal_sensitive_access_authorized_select
ON public.internal_sensitive_access FOR SELECT TO authenticated
USING (staff_user_id = (SELECT auth.uid()) OR (SELECT private.has_internal_permission('audit.read')));
CREATE POLICY technical_events_staff_select
ON public.technical_events FOR SELECT TO authenticated
USING ((SELECT private.has_internal_permission('technical.read')));
CREATE POLICY internal_build_requests_staff_select
ON public.internal_build_requests FOR SELECT TO authenticated
USING (
  requested_by = (SELECT auth.uid())
  OR (SELECT private.has_internal_permission('build.approve'))
);

-- Add internal read access without removing compatibility policies used by the
-- legacy shell. Compatibility policies are removed only after both pilots.
DO $policies$
DECLARE table_name text;
BEGIN
  FOREACH table_name IN ARRAY ARRAY[
    'organizations', 'organization_members', 'plans', 'plan_versions', 'features',
    'plan_features', 'plan_limits', 'subscriptions', 'usage_counters', 'usage_events',
    'active_sessions', 'support_tickets', 'support_ticket_events',
    'support_sla_policies', 'organization_onboarding', 'subscription_audit_events',
    'subscription_settings'
  ] LOOP
    EXECUTE format(
      'CREATE POLICY internal_console_staff_select ON public.%I FOR SELECT TO authenticated USING ((SELECT private.has_internal_permission(''console.read'')))',
      table_name
    );
  END LOOP;
END;
$policies$;

DO $owner_write_policies$
DECLARE table_name text;
BEGIN
  FOREACH table_name IN ARRAY ARRAY[
    'organizations', 'plans', 'plan_versions', 'features', 'plan_features',
    'plan_limits', 'subscriptions', 'support_sla_policies',
    'organization_onboarding', 'subscription_settings'
  ] LOOP
    EXECUTE format(
      'CREATE POLICY internal_console_owner_write ON public.%I FOR ALL TO authenticated USING ((SELECT private.has_internal_permission(''commercial.write''))) WITH CHECK ((SELECT private.has_internal_permission(''commercial.write'')))',
      table_name
    );
  END LOOP;
END;
$owner_write_policies$;

CREATE POLICY internal_console_vistorias_select
ON public.vistorias FOR SELECT TO authenticated
USING (
  organization_id IS NOT NULL
  AND (SELECT private.can_access_sensitive_customer('organization:' || organization_id::text))
);
CREATE POLICY internal_console_agendamentos_select
ON public.agendamentos FOR SELECT TO authenticated
USING (
  organization_id IS NOT NULL
  AND (SELECT private.can_access_sensitive_customer('organization:' || organization_id::text))
);

CREATE OR REPLACE FUNCTION public.get_internal_staff_profile()
RETURNS jsonb
LANGUAGE plpgsql STABLE SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE staff public.internal_staff;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'authentication_required' USING ERRCODE = '42501';
  END IF;

  SELECT * INTO staff
  FROM public.internal_staff
  WHERE user_id = auth.uid() AND status = 'active';

  IF staff.id IS NULL THEN RETURN NULL; END IF;

  RETURN jsonb_build_object(
    'id', staff.id,
    'user_id', staff.user_id,
    'role', staff.role,
    'status', staff.status,
    'display_name', staff.display_name,
    'permissions', to_jsonb(private.internal_permissions(staff.role)),
    'assurance_level', COALESCE(auth.jwt()->>'aal', 'aal1')
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.record_internal_access_denied(
  p_action text,
  p_target_type text DEFAULT NULL,
  p_target_id text DEFAULT NULL,
  p_reason text DEFAULT NULL
)
RETURNS void
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'authentication_required' USING ERRCODE = '42501';
  END IF;
  INSERT INTO public.internal_access_events(
    actor_id, actor_role, action, target_type, target_id, result, reason
  ) VALUES (
    auth.uid(), private.current_internal_role(), left(p_action, 120),
    left(p_target_type, 80), left(p_target_id, 200), 'denied', left(p_reason, 500)
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.manage_internal_staff(
  p_user_id uuid,
  p_role text,
  p_status text,
  p_reason text,
  p_operation_id uuid
)
RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  actor uuid := auth.uid();
  previous public.internal_staff;
  updated public.internal_staff;
  previous_result jsonb;
  v_request_hash text;
BEGIN
  IF NOT private.has_internal_permission('staff.manage', actor) THEN
    RAISE EXCEPTION 'staff_management_not_allowed' USING ERRCODE = '42501';
  END IF;
  IF NOT private.has_aal2() THEN
    RAISE EXCEPTION 'aal2_required' USING ERRCODE = '42501';
  END IF;
  IF p_role NOT IN ('owner', 'developer') OR p_status NOT IN ('active', 'suspended', 'removed') THEN
    RAISE EXCEPTION 'invalid_staff_state';
  END IF;
  IF char_length(trim(p_reason)) < 8 THEN RAISE EXCEPTION 'reason_required'; END IF;

  v_request_hash := md5(concat_ws('|', p_user_id, p_role, p_status, trim(p_reason)));
  SELECT result INTO previous_result
  FROM public.internal_operations
  WHERE actor_id = actor AND operation_id = p_operation_id AND request_hash = v_request_hash;
  IF previous_result IS NOT NULL THEN RETURN previous_result; END IF;

  INSERT INTO public.internal_operations(operation_id, actor_id, action, request_hash)
  VALUES (p_operation_id, actor, 'staff.manage', v_request_hash);

  SELECT * INTO previous FROM public.internal_staff WHERE user_id = p_user_id FOR UPDATE;
  INSERT INTO public.internal_staff(user_id, role, status, created_by)
  VALUES (p_user_id, p_role, p_status, actor)
  ON CONFLICT (user_id) DO UPDATE SET role = EXCLUDED.role, status = EXCLUDED.status
  RETURNING * INTO updated;

  previous_result := jsonb_build_object('ok', true, 'staff', to_jsonb(updated));
  UPDATE public.internal_operations
  SET status = 'succeeded', result = previous_result, completed_at = now()
  WHERE actor_id = actor AND operation_id = p_operation_id;

  INSERT INTO public.internal_access_events(
    actor_id, actor_role, action, target_type, target_id, result, reason, metadata
  ) VALUES (
    actor, private.current_internal_role(actor), 'staff.manage', 'internal_staff',
    p_user_id::text, 'allowed', left(p_reason, 500),
    jsonb_build_object(
      'before', CASE WHEN previous.id IS NULL THEN NULL ELSE jsonb_build_object('role', previous.role, 'status', previous.status) END,
      'after', jsonb_build_object('role', updated.role, 'status', updated.status)
    )
  );
  RETURN previous_result;
EXCEPTION WHEN unique_violation THEN
  SELECT result INTO previous_result
  FROM public.internal_operations
  WHERE actor_id = actor AND operation_id = p_operation_id;
  IF previous_result IS NOT NULL THEN RETURN previous_result; END IF;
  RAISE;
END;
$$;

CREATE OR REPLACE FUNCTION public.request_sensitive_support_access(
  p_customer_key text,
  p_ticket_id uuid,
  p_reason text
)
RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE ticket public.support_tickets; access_id uuid;
BEGIN
  IF NOT private.has_internal_permission('customer.sensitive.request') THEN
    RAISE EXCEPTION 'sensitive_access_not_allowed' USING ERRCODE = '42501';
  END IF;
  IF NOT private.has_aal2() THEN
    RAISE EXCEPTION 'aal2_required' USING ERRCODE = '42501';
  END IF;
  IF char_length(trim(p_reason)) < 8 THEN RAISE EXCEPTION 'reason_required'; END IF;

  SELECT * INTO ticket FROM public.support_tickets WHERE id = p_ticket_id;
  IF ticket.id IS NULL OR ticket.status NOT IN ('open', 'in_progress', 'waiting_customer') THEN
    RAISE EXCEPTION 'active_support_ticket_required' USING ERRCODE = '42501';
  END IF;
  IF p_customer_key <> COALESCE('organization:' || ticket.organization_id::text, 'user:' || ticket.user_id::text) THEN
    RAISE EXCEPTION 'ticket_customer_mismatch' USING ERRCODE = '42501';
  END IF;

  INSERT INTO public.internal_sensitive_access(
    staff_user_id, customer_key, ticket_id, reason, expires_at
  ) VALUES (auth.uid(), p_customer_key, p_ticket_id, trim(p_reason), now() + interval '60 minutes')
  RETURNING id INTO access_id;

  INSERT INTO public.internal_access_events(
    actor_id, actor_role, action, target_type, target_id, result, reason,
    metadata
  ) VALUES (
    auth.uid(), private.current_internal_role(), 'customer.sensitive.access',
    'customer', p_customer_key, 'allowed', left(p_reason, 500),
    jsonb_build_object('ticket_id', p_ticket_id, 'access_id', access_id, 'expires_in_minutes', 60)
  );
  RETURN jsonb_build_object('ok', true, 'access_id', access_id, 'expires_in_minutes', 60);
END;
$$;

CREATE OR REPLACE FUNCTION public.ingest_technical_event(
  p_event_key uuid,
  p_organization_id uuid,
  p_app_version text,
  p_platform text,
  p_category text,
  p_severity text,
  p_correlation_id text,
  p_summary text,
  p_metadata jsonb DEFAULT '{}'::jsonb
)
RETURNS bigint
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE event_id bigint;
BEGIN
  IF NOT private.has_internal_permission('technical.write') THEN
    RAISE EXCEPTION 'technical_event_not_allowed' USING ERRCODE = '42501';
  END IF;
  INSERT INTO public.technical_events(
    event_key, organization_id, user_id, app_version, platform, category,
    severity, correlation_id, summary, metadata
  ) VALUES (
    p_event_key, p_organization_id, auth.uid(), nullif(left(p_app_version, 50), ''),
    p_platform, p_category, p_severity, nullif(left(p_correlation_id, 120), ''),
    left(trim(p_summary), 500), private.sanitize_internal_metadata(p_metadata)
  )
  ON CONFLICT (event_key) DO UPDATE SET event_key = EXCLUDED.event_key
  RETURNING id INTO event_id;
  RETURN event_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.request_internal_build(
  p_operation_id uuid,
  p_provider text,
  p_environment text,
  p_version text,
  p_profile text,
  p_changelog text,
  p_reason text
)
RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE request public.internal_build_requests; initial_status text;
BEGIN
  IF NOT private.has_internal_permission('build.request') THEN
    RAISE EXCEPTION 'build_request_not_allowed' USING ERRCODE = '42501';
  END IF;
  IF NOT private.has_aal2() THEN RAISE EXCEPTION 'aal2_required' USING ERRCODE = '42501'; END IF;
  IF p_environment NOT IN ('development', 'preview', 'production') THEN RAISE EXCEPTION 'invalid_environment'; END IF;
  IF char_length(trim(p_reason)) < 8 THEN RAISE EXCEPTION 'reason_required'; END IF;
  initial_status := CASE WHEN p_environment = 'production' THEN 'pending' ELSE 'approved' END;

  INSERT INTO public.internal_build_requests(
    operation_id, requested_by, provider, environment, version, profile,
    changelog, reason, status
  ) VALUES (
    p_operation_id, auth.uid(), p_provider, p_environment, left(p_version, 50),
    left(p_profile, 50), left(COALESCE(p_changelog, ''), 5000), trim(p_reason), initial_status
  )
  ON CONFLICT (requested_by, operation_id) DO UPDATE
    SET operation_id = EXCLUDED.operation_id
  RETURNING * INTO request;

  INSERT INTO public.internal_access_events(
    actor_id, actor_role, action, target_type, target_id, result, reason, metadata
  ) VALUES (
    auth.uid(), private.current_internal_role(), 'build.request', 'build_request',
    request.id::text, 'allowed', left(p_reason, 500),
    jsonb_build_object('environment', request.environment, 'status', request.status, 'version', request.version)
  );
  RETURN jsonb_build_object('ok', true, 'request_id', request.id, 'status', request.status);
END;
$$;

CREATE OR REPLACE FUNCTION public.decide_internal_build(
  p_request_id uuid,
  p_approve boolean,
  p_reason text
)
RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE request public.internal_build_requests;
BEGIN
  IF NOT private.has_internal_permission('build.approve') THEN
    RAISE EXCEPTION 'build_approval_not_allowed' USING ERRCODE = '42501';
  END IF;
  IF NOT private.has_aal2() THEN RAISE EXCEPTION 'aal2_required' USING ERRCODE = '42501'; END IF;
  IF char_length(trim(p_reason)) < 8 THEN RAISE EXCEPTION 'reason_required'; END IF;

  SELECT * INTO request FROM public.internal_build_requests WHERE id = p_request_id FOR UPDATE;
  IF request.id IS NULL OR request.status <> 'pending' THEN RAISE EXCEPTION 'build_request_not_pending'; END IF;
  IF request.requested_by = auth.uid() THEN RAISE EXCEPTION 'self_approval_not_allowed' USING ERRCODE = '42501'; END IF;

  UPDATE public.internal_build_requests
  SET status = CASE WHEN p_approve THEN 'approved' ELSE 'rejected' END,
      approved_by = auth.uid(), decided_at = now()
  WHERE id = p_request_id
  RETURNING * INTO request;

  INSERT INTO public.internal_access_events(
    actor_id, actor_role, action, target_type, target_id, result, reason, metadata
  ) VALUES (
    auth.uid(), private.current_internal_role(), 'build.decide', 'build_request',
    request.id::text, 'allowed', left(p_reason, 500),
    jsonb_build_object('status', request.status, 'environment', request.environment, 'version', request.version)
  );
  RETURN jsonb_build_object('ok', true, 'request_id', request.id, 'status', request.status);
END;
$$;

-- Remote session termination is a high-risk action for internal staff.
CREATE OR REPLACE FUNCTION public.end_active_session(
  p_session_id uuid,
  p_reason text DEFAULT 'remote_termination'
)
RETURNS boolean
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE target public.active_sessions; actor uuid := auth.uid(); internal_role text;
BEGIN
  SELECT * INTO target FROM public.active_sessions WHERE id = p_session_id FOR UPDATE;
  IF target.id IS NULL THEN RETURN false; END IF;
  internal_role := private.current_internal_role(actor);

  IF internal_role IS NOT NULL THEN
    IF NOT private.has_internal_permission('session.terminate', actor) THEN
      RAISE EXCEPTION 'session_termination_not_allowed' USING ERRCODE = '42501';
    END IF;
    IF target.user_id <> actor AND NOT private.has_aal2() THEN
      RAISE EXCEPTION 'aal2_required' USING ERRCODE = '42501';
    END IF;
    IF target.user_id <> actor AND char_length(trim(p_reason)) < 8 THEN
      RAISE EXCEPTION 'reason_required';
    END IF;
  ELSIF target.user_id <> actor
    AND NOT private.is_owner_admin(actor)
    AND NOT (
      target.organization_id = private.current_organization_id(actor)
      AND private.organization_role(target.organization_id, actor) IN ('owner', 'coordinator', 'supervisor')
    ) THEN
    RAISE EXCEPTION 'session_termination_not_allowed' USING ERRCODE = '42501';
  END IF;

  UPDATE public.active_sessions
  SET status = 'revoked', ended_at = now(), ended_by = actor, end_reason = left(trim(p_reason), 200)
  WHERE id = p_session_id AND status = 'active';

  INSERT INTO public.subscription_audit_events(
    organization_id, actor_id, event_type, entity_type, entity_id, metadata
  ) VALUES (
    target.organization_id, actor, 'session_ended', 'active_session', p_session_id::text,
    jsonb_build_object('reason', left(trim(p_reason), 200))
  );
  IF internal_role IS NOT NULL THEN
    INSERT INTO public.internal_access_events(
      actor_id, actor_role, action, target_type, target_id, result, reason
    ) VALUES (actor, internal_role, 'session.terminate', 'active_session', p_session_id::text, 'allowed', left(trim(p_reason), 500));
  END IF;
  RETURN true;
END;
$$;

REVOKE ALL ON FUNCTION public.get_internal_staff_profile(),
  public.record_internal_access_denied(text, text, text, text),
  public.manage_internal_staff(uuid, text, text, text, uuid),
  public.request_sensitive_support_access(text, uuid, text),
  public.ingest_technical_event(uuid, uuid, text, text, text, text, text, text, jsonb),
  public.request_internal_build(uuid, text, text, text, text, text, text),
  public.decide_internal_build(uuid, boolean, text),
  public.end_active_session(uuid, text)
FROM PUBLIC, anon;

GRANT EXECUTE ON FUNCTION public.get_internal_staff_profile(),
  public.record_internal_access_denied(text, text, text, text),
  public.manage_internal_staff(uuid, text, text, text, uuid),
  public.request_sensitive_support_access(text, uuid, text),
  public.ingest_technical_event(uuid, uuid, text, text, text, text, text, text, jsonb),
  public.request_internal_build(uuid, text, text, text, text, text, text),
  public.decide_internal_build(uuid, boolean, text),
  public.end_active_session(uuid, text)
TO authenticated;

CREATE OR REPLACE FUNCTION public.list_internal_customers(
  p_search text DEFAULT NULL,
  p_status text DEFAULT NULL,
  p_limit integer DEFAULT 25,
  p_offset integer DEFAULT 0
)
RETURNS jsonb
LANGUAGE plpgsql STABLE SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE result jsonb;
BEGIN
  IF NOT private.has_internal_permission('customer.read') THEN
    RAISE EXCEPTION 'customer_read_not_allowed' USING ERRCODE = '42501';
  END IF;

  WITH customers AS (
    SELECT
      'organization:' || o.id::text AS customer_id,
      'organization'::text AS kind,
      o.id AS subject_id,
      o.display_name,
      o.legal_name,
      o.municipality_name,
      o.state_code,
      o.status,
      CASE WHEN private.current_internal_role() = 'owner' THEN o.contact_name END AS contact_name,
      CASE WHEN private.current_internal_role() = 'owner' THEN o.contact_email END AS contact_email,
      s.status AS subscription_status,
      p.name AS plan_name,
      (SELECT count(*)::integer FROM public.organization_members m WHERE m.organization_id = o.id AND m.status = 'active') AS active_users,
      o.updated_at AS last_activity_at
    FROM public.organizations o
    LEFT JOIN LATERAL (
      SELECT sub.* FROM public.subscriptions sub
      WHERE sub.organization_id = o.id
      ORDER BY sub.created_at DESC LIMIT 1
    ) s ON true
    LEFT JOIN public.plans p ON p.id = s.plan_id
    UNION ALL
    SELECT
      'user:' || u.uid::text,
      'individual'::text,
      u.uid,
      COALESCE(NULLIF(trim(u.name), ''), 'Conta individual'),
      NULL::text,
      u.municipio,
      NULL::text,
      CASE WHEN u."isApproved" THEN 'active' ELSE 'onboarding' END,
      NULL::text,
      CASE WHEN private.current_internal_role() = 'owner' THEN u.email END,
      s.status,
      p.name,
      1,
      u."createdAt"
    FROM public.users u
    LEFT JOIN LATERAL (
      SELECT sub.* FROM public.subscriptions sub
      WHERE sub.user_id = u.uid
      ORDER BY sub.created_at DESC LIMIT 1
    ) s ON true
    LEFT JOIN public.plans p ON p.id = s.plan_id
    WHERE u.organization_id IS NULL AND u.role <> 'master_admin'
  ), filtered AS (
    SELECT * FROM customers c
    WHERE (p_status IS NULL OR p_status = '' OR c.status = p_status)
      AND (
        p_search IS NULL OR trim(p_search) = ''
        OR c.display_name ILIKE '%' || trim(p_search) || '%'
        OR COALESCE(c.legal_name, '') ILIKE '%' || trim(p_search) || '%'
        OR COALESCE(c.municipality_name, '') ILIKE '%' || trim(p_search) || '%'
        OR COALESCE(c.contact_name, '') ILIKE '%' || trim(p_search) || '%'
        OR COALESCE(c.contact_email, '') ILIKE '%' || trim(p_search) || '%'
        OR c.customer_id ILIKE '%' || trim(p_search) || '%'
      )
  ), page AS (
    SELECT * FROM filtered
    ORDER BY display_name, customer_id
    LIMIT greatest(1, least(p_limit, 100)) OFFSET greatest(p_offset, 0)
  )
  SELECT jsonb_build_object(
    'items', COALESCE((SELECT jsonb_agg(to_jsonb(page)) FROM page), '[]'::jsonb),
    'total', (SELECT count(*) FROM filtered),
    'limit', greatest(1, least(p_limit, 100)),
    'offset', greatest(p_offset, 0)
  ) INTO result;
  RETURN result;
END;
$$;

REVOKE ALL ON FUNCTION public.list_internal_customers(text, text, integer, integer) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.list_internal_customers(text, text, integer, integer) TO authenticated;

CREATE OR REPLACE FUNCTION public.mutate_internal_support_ticket(
  p_ticket_id uuid,
  p_action text,
  p_value text,
  p_message text,
  p_operation_id uuid
)
RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE actor uuid := auth.uid(); ticket public.support_tickets; v_hash text; prior jsonb; response jsonb;
BEGIN
  IF NOT private.has_internal_permission('support.write', actor) THEN RAISE EXCEPTION 'support_write_not_allowed' USING ERRCODE = '42501'; END IF;
  IF p_action NOT IN ('status', 'priority', 'assignee', 'message', 'note') THEN RAISE EXCEPTION 'invalid_support_action'; END IF;
  v_hash := md5(concat_ws('|', p_ticket_id, p_action, p_value, p_message));
  SELECT result INTO response FROM public.internal_operations WHERE actor_id = actor AND operation_id = p_operation_id AND request_hash = v_hash;
  IF response IS NOT NULL THEN RETURN response; END IF;
  INSERT INTO public.internal_operations(operation_id, actor_id, action, request_hash) VALUES (p_operation_id, actor, 'support.' || p_action, v_hash);
  SELECT * INTO ticket FROM public.support_tickets WHERE id = p_ticket_id FOR UPDATE;
  IF ticket.id IS NULL THEN RAISE EXCEPTION 'ticket_not_found'; END IF;
  prior := jsonb_build_object('status', ticket.status, 'priority', ticket.priority, 'assigned_to', ticket.assigned_to);
  IF p_action = 'status' THEN
    IF p_value NOT IN ('open','in_progress','waiting_customer','resolved','closed') THEN RAISE EXCEPTION 'invalid_status'; END IF;
    UPDATE public.support_tickets SET status = p_value, updated_at = now() WHERE id = p_ticket_id;
  ELSIF p_action = 'priority' THEN
    IF p_value NOT IN ('low','normal','high','critical') THEN RAISE EXCEPTION 'invalid_priority'; END IF;
    UPDATE public.support_tickets SET priority = p_value, updated_at = now() WHERE id = p_ticket_id;
  ELSIF p_action = 'assignee' THEN
    UPDATE public.support_tickets SET assigned_to = nullif(p_value, '')::uuid, updated_at = now() WHERE id = p_ticket_id;
  END IF;
  INSERT INTO public.support_ticket_events(ticket_id, actor_id, event_type, message, metadata)
  VALUES (p_ticket_id, actor, p_action, CASE WHEN p_action IN ('message','note') THEN left(trim(p_message), 5000) ELSE NULL END,
    private.sanitize_internal_metadata(jsonb_build_object('value', left(p_value, 200), 'visibility', CASE WHEN p_action='note' THEN 'internal' ELSE 'shared' END)));
  response := jsonb_build_object('ok', true, 'ticket_id', p_ticket_id, 'action', p_action);
  UPDATE public.internal_operations SET status='succeeded', result=response, completed_at=now() WHERE actor_id=actor AND operation_id=p_operation_id;
  INSERT INTO public.internal_access_events(actor_id, actor_role, action, target_type, target_id, result, metadata)
  VALUES (actor, private.current_internal_role(actor), 'support.' || p_action, 'support_ticket', p_ticket_id::text, 'allowed',
    jsonb_build_object('before', prior, 'value', left(p_value, 200)));
  RETURN response;
END;
$$;
REVOKE ALL ON FUNCTION public.mutate_internal_support_ticket(uuid, text, text, text, uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mutate_internal_support_ticket(uuid, text, text, text, uuid) TO authenticated;
